
spring:
  cloud:
    nacos:
      discovery:
        cluster-name: lanswon
        server-addr: 192.168.44.78:8848
---
spring:
  datasource:
    druid:
      url: jdbc:mysql://rm-uf6uj9b175xy597fl3o.mysql.rds.aliyuncs.com:3306/estate?characterEncoding=utf8&useSSL=false
      username: jaswine
      password: Jasmine1017